seed = 2

[data]
cat_policy = 'indices'
normalization = 'quantile'
path = 'data/vehicleNorm'

[model]
activation = 'reglu'
attention_dropout = 0.4196916057583969
d_ffn_factor = 2.509054785477425
d_token = 144
ffn_dropout = 0.1764610276920801
initialization = 'kaiming'
n_heads = 8
n_layers = 2
prenormalization = true
residual_dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 3.201968805382119e-05
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 1.183332535426216e-05
