seed = 0

[data]
normalization = 'quantile'
path = 'data/california_housing'
y_policy = 'mean_std'

[model]
activation = 'reglu'
attention_dropout = 0.3125472211091234
d_ffn_factor = 1.962840671342713
d_token = 96
ffn_dropout = 0.2365875616631682
initialization = 'kaiming'
n_heads = 8
n_layers = 2
prenormalization = true
residual_dropout = 0.0
token_bias = false
token_cat_bias = false

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.0001828833902272113
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 0.0002323876587702115
