seed = 1

[data]
cat_policy = 'indices'
path = 'data/broken_machine'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = true

[model]
colsample_bytree = 0.9693425391673653
learning_rate = 0.09440740156408886
min_child_samples = 95
min_child_weight = 0.03398774230105511
n_estimators = 2000
n_jobs = 10
num_leaves = 92
reg_lambda = 0.0
subsample = 0.6214078432303646
