seed = 3

[data]
normalization = 'quantile'
path = 'data/microsoft'
y_policy = 'mean_std'

[model]
activation = 'reglu'
attention_dropout = 0.2367026970034473
d_ffn_factor = 1.333333333333333
d_token = 104
ffn_dropout = 0.08782495176671656
initialization = 'kaiming'
n_heads = 8
n_layers = 2
prenormalization = true
residual_dropout = 0.0

[training]
batch_size = 1024
eval_batch_size = 8192
lr = 4.69162138270869e-05
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 0.0009997786518737089
