seed = 2

[data]
normalization = 'quantile'
path = 'data/microsoft'
y_policy = 'mean_std'

[model]
activation = 'reglu'
attention_dropout = 0.1558926086578752
d_ffn_factor = 1.333333333333333
d_token = 192
ffn_dropout = 0.1400961316024743
initialization = 'kaiming'
n_heads = 8
n_layers = 5
prenormalization = true
residual_dropout = 0.0
token_bias = false
token_cat_bias = false

[training]
batch_size = 1024
eval_batch_size = 8192
lr = 0.0001688316076012206
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 0.0006582641175048847
