seed = 1

[data]
cat_policy = 'indices'
path = 'data/vehicleNorm'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = true

[model]
colsample_bytree = 0.514007408896976
learning_rate = 0.02991570469577435
min_child_samples = 44
min_child_weight = 0.0005612888499599646
n_estimators = 2000
n_jobs = 10
num_leaves = 87
reg_lambda = 0.0
subsample = 0.8526319497749828
