seed = 2

[data]
cat_policy = 'indices'
path = 'data/jannis'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = true

[model]
colsample_bytree = 0.57244265267845
learning_rate = 0.0205534155481011
min_child_samples = 45
min_child_weight = 1.573199523319862e-05
n_estimators = 2000
n_jobs = 20
num_leaves = 96
reg_lambda = 0.0
subsample = 0.6460295916225417
