seed = 8

[data]
path = 'data/microsoft'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = true

[model]
colsample_bytree = 0.6630691036117577
learning_rate = 0.03409718458931771
min_child_samples = 50
min_child_weight = 0.02285281560670613
n_estimators = 2000
n_jobs = 20
num_leaves = 100
reg_lambda = 0.0
subsample = 0.5851579305722739
