seed = 4

[data]
cat_policy = 'indices'
normalization = 'quantile'
path = 'data/broken_machine'

[model]
activation = 'reglu'
attention_dropout = 0.4178066644252025
d_ffn_factor = 1.333333333333333
d_token = 432
ffn_dropout = 0.06337002372307488
initialization = 'kaiming'
n_heads = 8
n_layers = 3
prenormalization = true
residual_dropout = 0.0

[training]
batch_size = 1024
eval_batch_size = 8192
lr = 7.523375809438358e-05
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 0.0002871929965055266
