seed = 5

[data]
normalization = 'quantile'
path = 'data/covtype'

[model]
activation = 'reglu'
attention_dropout = 0.02248299429741116
d_ffn_factor = 1.333333333333333
d_token = 272
ffn_dropout = 0.008226274405180006
initialization = 'kaiming'
n_heads = 8
n_layers = 2
prenormalization = true
residual_dropout = 0.0
token_bias = false
token_cat_bias = false

[training]
batch_size = 1024
eval_batch_size = 8192
lr = 3.159918172943631e-05
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 8.254922539019199e-06
