seed = 1

[data]
cat_policy = 'indices'
normalization = 'quantile'
path = 'data/nomao'

[model]
activation = 'reglu'
attention_dropout = 0.1626716818652701
d_ffn_factor = 1.845241078904277
d_token = 96
ffn_dropout = 0.06559127961509764
initialization = 'kaiming'
n_heads = 8
n_layers = 4
prenormalization = true
residual_dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.0001844643568489571
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 2.942391900026969e-06
