seed = 5

[data]
normalization = 'quantile'
path = 'data/jannis'

[model]
activation = 'reglu'
attention_dropout = 0.4194914895568438
d_ffn_factor = 1.061031416526688
d_token = 288
ffn_dropout = 0.4632881116664471
initialization = 'kaiming'
n_heads = 8
n_layers = 4
prenormalization = false
residual_dropout = 0.0

[training]
batch_size = 512
eval_batch_size = 8192
lr = 0.0001089430445312344
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 2.897993930091118e-05
