seed = 9

[data]
cat_policy = 'indices'
path = 'data/nomao'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = true

[model]
colsample_bytree = 0.8049146089492032
learning_rate = 0.0369702442162517
min_child_samples = 78
min_child_weight = 0.01342525377980585
n_estimators = 2000
n_jobs = 20
num_leaves = 73
reg_lambda = 0.0
subsample = 0.5899126531544889
